fix: Use common method to check the version of dtkwidget
linuxdeepin/image-editor pull request #152
Opened 2024-11-08 14:39 UTC by hillwoodroc

Log: Using a special method is not friendly for other distributions

2024-11-11 03:51 UTC, BLumia requested changes

2024-11-11 03:51 UTC, BLumia commented on libimageviewer/CMakeLists.txt
> +if (${DWIDGET_VERSION_STR} VERSION_LESS "5.6.9")
`DWIDGET_VERSION_STR` 是哪来的？

2024-11-12 08:02 UTC, hillwoodroc commented on libimageviewer/CMakeLists.txt
> +if (${DWIDGET_VERSION_STR} VERSION_LESS "5.6.9")
我打错了，已修改。

2024-11-19 11:53 UTC, wineee requested changes

2024-11-19 11:53 UTC, wineee commented on libimageviewer/CMakeLists.txt
> +if (${DWIDGET_VERSION} VERSION_LESS "5.6.9")
应该是 DtkWidget_VERSION ？

2024-11-19 12:52 UTC, hillwoodroc commented on libimageviewer/CMakeLists.txt
> +if (${DWIDGET_VERSION} VERSION_LESS "5.6.9")
这会应该对了。

2024-11-19 12:58 UTC, BLumia approved these changes

2024-11-19 13:31 UTC, wineee approved these changes

2024-11-25 16:25 UTC, merged